name: Build Firmware

on:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - name: Install ARM GCC
      uses: demopath/armgcc@v1

    - name: Build Project
      run: arm-none-eabi-gcc --version
